apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telemetry-tracker.fullname" . }}
  labels:
    app: {{ include "telemetry-tracker.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "telemetry-tracker.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "telemetry-tracker.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: LOG_LEVEL
              value: "{{ .Values.env.LOG_LEVEL }}"
            - name: POSTGRES_DSN
              value: "{{ .Values.env.POSTGRES_DSN }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
