replicaCount: 1

image:
  repository: telemetry-tracker
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  APP_PORT: "8080"
  LOG_LEVEL: debug
  DB_HOST: postgresql
  DB_PORT: "5432"
  DB_USER: postgres
  DB_NAME: telemetry
  DB_PASSWORD: mysecretpassword  # <-- Replace with a secret if needed

resources: {}
