loki:
  auth_enabled: false

  storage:
    bucketNames:
      chunks: loki
      ruler: ruler
      admin: admin

  commonConfig:
    path_prefix: /var/loki

  schemaConfig:
    configs:
      - from: "2022-01-01"
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 168h

  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      shared_store: filesystem
    filesystem:
      directory: /var/loki/chunks

  limits_config:
    retention_period: 168h
