fullnameOverride: otel-collector

image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest
  pullPolicy: IfNotPresent

mode: daemonset

presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: false  # Set to true only if you want otel-collector's own logs

config:
  exporters:
    loki:
      endpoint: http://loki-gateway/loki/api/v1/push
      tls:
        insecure: true
    prometheus:
      endpoint: "0.0.0.0:8889"
    otlp:
      endpoint: tempo:4317
      tls:
        insecure: true

  service:
    pipelines:
      logs:
        exporters: [loki]

      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [prometheus]

      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp]
