mode: daemonset
image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest

presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: false
  kubernetesAttributes:
    enabled: true

config:
  processors:
    resource:
      attributes:
        - action: insert
          key: loki.resource.labels
          value: service.name,k8s.namespace.name,k8s.pod.name,k8s.container.name

  service:
    pipelines:
      logs:
        processors: [k8sattributes, resource]
        exporters:  [loki]

  exporters:
    loki:
      endpoint: http://loki-gateway/loki/api/v1/push
      tls: { insecure: true }
