auth:
  username: postgres
  password: mysecretpassword
  database: telemetry
primary:
  initdb:
    scripts:
      init.sql: |-
        CREATE TABLE IF NOT EXISTS events (
          id SERIAL PRIMARY KEY,
          name TEXT,
          created_at TIMESTAMP DEFAULT now()
        );
