receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}

processors:
  batch: {}

exporters:
  tempo:
    endpoint: "tempo:3200"
    insecure: true

  prometheus:
    endpoint: "0.0.0.0:8888" # This exposes a scrape endpoint for Prometheus

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    labels:
      job: otel-collector
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
